#!/bin/sh
# author: syz

# 获取提交信息文件相对路径
FILENAME=$1

# python的虚拟路径和项目路径
INSTALL_PYTHON='D:\pythonprojects\pyautoguis\scripts\python.exe'
PROJECT_PATH="D:\PythonProjects\Project\Python36\Lib\e_rpa"
USER_NAME=$(git config user.name)

# 执行
cd $PROJECT_PATH
$INSTALL_PYTHON "${PROJECT_PATH}\git_hook\message_check.py"